### ISSUE TITLE
Is it possible to specify blob name dynamically?

### ISSUE THREAD

**Issue by kalexii** [chriswill/serilog-sinks-azureblobstorage#10]
It's in the title. Say, I want to calculate the name of the blob based on current date? And have that name changed once the next day comes?

**Comment by jvanderbiest** [comment]
@kalexii I think you could use rolling files for this, a functionality that was recently implemented https://github.com/chriswill/serilog-sinks-azureblobstorage/pull/7

Would be good to add that sample to the JSON configuration on the Readme.md.

**Comment by chriswill** [comment]
Right now you can browse through the [unit test](https://github.com/chriswill/serilog-sinks-azureblobstorage/blob/master/Serilog.Sinks.AzureBlobStorage.UnitTest/BlobNameFactoryUT.cs) to see what types of names are supported.  If you give the log file a name like "{yyyy}/{MM}/{dd}.txt" or "{yyyy}/{MM}/{dd}/log.txt" it will create a new file every day.
