### ISSUE TITLE
Filters not working for WriteTo.AzureBlobStorage

### ISSUE THREAD

**Issue by dariusmunteanu** [chriswill/serilog-sinks-azureblobstorage#104]
If I add a Serilog filter the logging doesn't work anymore, not even in the console.

I tried with both an expression:
`.Filter.ByExcluding("@l= 'Debug' and SourceContext like '%Microsoft%'")`

And a predicate:
`.Filter.ByIncludingOnly(e => e.Level == LogEventLevel.Debug)`

**Comment by chriswill** [comment]
I'm not seeing this.

I tested filters using v4.0.0 of the sink using this style and it worked as expected.

                var app = Host
                    .CreateDefaultBuilder(args)
                    .ConfigureServices(services => services.AddHostedService<PrintTimeService>())
                    .UseSerilog((context, services, configuration) => configuration
                        .ReadFrom.Configuration(context.Configuration).Filter.ByIncludingOnly(x => x.Level == LogEventLevel.Information)
                    )
                    .Build();
