### ISSUE TITLE
After 6 hours I can't get this to work - at all

### ISSUE THREAD

**Issue by DavidThielen** [chriswill/serilog-sinks-azureblobstorage#105]
Is there a way to find out what this sink is doing and why it is failing. With various configurations I can get it to log, but my pages don't come up. Or my pages come up and it doesn't log.

[The specifics are her](https://stackoverflow.com/questions/77255633/trying-to-use-serilog-sinks-azureblobstorage-in-blazor)e. But my question is, how should one go about figuring out:

1. If log messages are not writing to the sink - why?
2. If this sink is causing my pages not to render - why?
3. How do I figure out how it is changing the log level for not Serilog targets?

thanks - dave

**Comment by DavidThielen** [comment]
[Here is a very simple/basic Blazor app that tries to use the azureblobstorage sink](https://www.dropbox.com/scl/fi/tnpnggdmw82538ke300li/Serilog_bug.zip?rlkey=tbpnb1mmzvcrimn3xbn3tr9e5&dl=1).

Neither sink (also has File) works. In addition, when the azureblobstorage is specified, it causes an exception when the app tries to load `Blazor_Logger_bug.styles.css` which then totally hoses rendering pages.

**Comment by chriswill** [comment]
This sink is not intended for use in Blazor.  I won't be doing testing or development with that target in mind, but I invite you to do so if you can.

**Comment by DavidThielen** [comment]
@chriswill I wrote my own LoggerProvider implementation because of this issue. [It's now up on GitHub](https://github.com/DavidThielen/TradeWindsLoggerProvider) if you want to use it to add Blazor support to your sink.
