### ISSUE TITLE
Serilog.Sinks.AzureBlobStorage.TaskExtensions.SyncContextSafeWait causing threadpool starvation

### ISSUE THREAD

**Issue by anandou** [chriswill/serilog-sinks-azureblobstorage#113]
See below stacktrace and advise on how to resolve this issue.

These threads are calling Task.Result and synchronously waiting on a Task object. The caller function identified for the maximum number of threads is **Serilog.Sinks.AzureBlobStorage.TaskExtensions.SyncContextSafeWait[**[System.__Canon, System.Private.CoreLib]].

HelperMethodFrame_1OBJ
System.Threading.ManualResetEventSlim.Wait
System.Threading.Tasks.Task.SpinThenBlockingWait
System.Threading.Tasks.Task.InternalWaitCore
System.Threading.Tasks.Task.InternalWait
System.Threading.Tasks.Task.Wait
System.Threading.Tasks.Task.Wait
**Serilog.Sinks.AzureBlobStorage.TaskExtensions.SyncContextSafeWait[[System.__Canon, System.Private.CoreLib]]
Serilog.Sinks.AzureBlobStorage.AzureBlobStorageSink.Emit
Serilog.Core.Sinks.SafeAggregateSink.Emit**
CT.Platform.Logging.Client.CustomSink+<>c__DisplayClass3_0.<Emit>b__0
System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop
System.Threading.Tasks.Task.ExecuteWithThreadLocal
System.Threading.ThreadPoolWorkQueue.Dispatch
System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart
DebuggerU2MCatchHandlerFrame

**Comment by chriswill** [comment]
The current version of the sink uses Serilog 4.0 and async methods.  Please refile if you see this in the current version and submit a PR to resolve, if possible.
