### ISSUE TITLE
Support log level in storageFileName

### ISSUE THREAD

**Issue by kurthamilton** [chriswill/serilog-sinks-azureblobstorage#116]
### Current functionality
`storageFileName` currently supports the following datetime placeholder tokens:
'y', 'M', 'd', 'H', 'm'

This allows for log files to have dynamic paths and/or names.
```
new LoggerConfiguration()
  .WriteTo
  .AzureBlobStorage(
    connectionString: "my-connection-string",
    storageFileName: "logs/{yyyy}/{MM}/log.{yyyyMMdd}.txt");
```

### Feature request
I would like to use the log level (Error, Info, Warning, etc) in the log filepath.

Would it be possible to either:
1. Support log level as a placeholder token, e.g. `storageFileName: "logs/{yyyy}/{MM}/log.{yyyyMMdd}.{Level}.txt"`
2. Inject a custom blob name factory into `AzureBlobStorage`, e.g.
```
new LoggerConfiguration()
  .WriteTo
  .AzureBlobStorage(
    connectionString: "my-connection-string",
    blobNameFactory: new MyBlobNameFactory());
```

**Comment by kurthamilton** [comment]
As a workaround I have created a second logger configured with a minimum log level

```
var logger = new LoggerConfiguration()
    .WriteTo
    .AzureBlobStorage(
        connectionString: "my-connection-string",
        storageFileName: "logs/log.{yyyyMMdd}.txt")
    .WriteTo
    .AzureBlobStorage(
        connectionString: "my-connection-string",
        storageFileName: "logs/errors.{yyyyMMdd}.txt",
        restrictedToMinimumLevel: LogEventLevel.Error)
    .CreateLogger();
```

This does meet the requirements of my use case, so my feature request is possibly redundant if nobody else thinks it could help them.

**Comment by chriswill** [comment]
The 4.0.0 version of the sink implements support for Levels in the file name exactly as you've shown.

**Comment by kurthamilton** [comment]
> The 4.0.0 version of the sink implements support for Levels in the file name exactly as you've shown.

Looks like that is newly released so I look forward to trying it out. Thanks!
