### ISSUE TITLE
Replace Microsoft.Extensions.Hosting with Microsoft.Extensions.Configuration.Abstractions

### ISSUE THREAD

**Issue by SymbioticKilla** [chriswill/serilog-sinks-azureblobstorage#119]
Hi @chriswill,

I think it is possible to replace a big Microsoft.Extensions.Hosting nuget with a smaller one: Microsoft.Extensions.Configuration.Abstractions. 
I have tested with Rebuild. 

Thanks!

**Comment by chriswill** [comment]
Yes, I see that.  Seems to build and run fine with the change.

Will push that an an update for System.Text.Json to resolve https://github.com/advisories/GHSA-hh2w-p6rv-4g7w in version 4.0.2 shortly.

**Comment by chriswill** [comment]
Version 4.0.2 now available https://www.nuget.org/packages/Serilog.Sinks.AzureBlobStorage/4.0.2
