### ISSUE TITLE
Azure Function App with Always On does not switch to new file

### ISSUE THREAD

**Issue by praveenpallekaate** [chriswill/serilog-sinks-azureblobstorage#123]
I have an Azure Func App that is running on Always On mode with below serilog blob settings.
```
            .WriteTo
            .AzureBlobStorage(
                connectionString: blobConnStr,
                storageContainerName: "applog",
                storageFileName: "applog\\{DateTime.Now.ToString("yyyy-MM-dd")}.txt",
                retainedBlobCountLimit: 20)
```
ILogger of Func app writes log to the file.
The file gets created in blob storage. But does not create a new file the next day instead continues to append existing file.
If i forcefully restart the func app only then a new file current date gets created.
Is it possible to add log to new files without manual restart of Func app?

**Comment by praveenpallekaate** [comment]
I'm using Serilog.Sinks.AzureBlobStorage 3.3.0 version. I'm going to try with latest 4.0.2 and see if any changes.

I tried to create a timer function that runs daily to recreate `Logger` as below, that did not help. Logs was written on same file.
```
Log.Logger = new LoggerConfiguration()
            .WriteTo
            .AzureBlobStorage(
                connectionString: blobConnStr,
                storageContainerName: "applog",
                storageFileName: "applog\\{DateTime.Now.ToString("yyyy-MM-dd")}.txt",
                retainedBlobCountLimit: 20)

Serilog.Log.CloseAndFlush();
```

**Comment by chriswill** [comment]
This is not the way that the storage file names are supposed to work.  Your file will always have the same name, because the configuration is only read once when the app is started up, and this is when DateTime.Now is run.

To make the file name roll over daily, you should follow the instructions on the home page and use a parameter with appropriate substitutions, like this:

Log.Logger = new LoggerConfiguration()
            .WriteTo
            .AzureBlobStorage(
                connectionString: blobConnStr,
                storageContainerName: "applog",
                storageFileName: "applog/{yyyy}-{MM}-{dd}.txt",
                retainedBlobCountLimit: 20)

Serilog.Log.CloseAndFlush();
