### ISSUE TITLE
Append blocks should be checked for size before sending to Blob Storage

### ISSUE THREAD

**Issue by DaanWasscher** [chriswill/serilog-sinks-azureblobstorage#16]
Hi,

When sending append blocks greater than 4MB Azure Blob Storage returns an error. The sink should check the size and if needed split the sending into multiple append blocks.

Br,
Daan

**Comment by jtermine** [comment]
Also, what happens if the blob has more than 50,000 blocks already?  It would need a mechanism to roll the log file to another blob.

**Comment by DaanWasscher** [comment]
Hi @chriswill,
I created a PR which would fix this and some other things. Please have a look.
#21 

/Daan

**Comment by chriswill** [comment]
Thanks for the contribution.

This issue is fixed in release 1.0.2
