### ISSUE TITLE
Default cloud blob provider fails when using a SAS token

### ISSUE THREAD

**Issue by DaanWasscher** [chriswill/serilog-sinks-azureblobstorage#17]
Hi,
I'm using a SAS token to give access to a specific container in my storage account. In this case the DefaultCloudBlobProvider cannot create the container and ends up in the catch block of the provider. But then the returned CloudAppendBlob is always null.

And in cases where the CloudAppendBlob can be created it seems to me that the rolling over to a new log file for a new day will not work. But I am not fully sure of that.

If you want I could make some PR's for the newly created issues...

Br,
Daan

**Comment by chriswill** [comment]
Hi @DaanWasscher , thanks for your issue reports.  If you'd like to submit PRs that would be awesome! Thanks for your interest in the project.

**Comment by DaanWasscher** [comment]
Hi @chriswill,
I created a PR which would fix this and some other things. Please have a look.
#21 

/Daan

**Comment by chriswill** [comment]
Thanks for the contribution.

This issue is fixed in release 1.0.2
