### ISSUE TITLE
Date not working for blob name

### ISSUE THREAD

**Issue by littleoz2** [chriswill/serilog-sinks-azureblobstorage#20]
I have used the same code you have for the rolling files in your readme but my file name is coming out as: "{yyyy}{MM}{dd}.txt", I even tried "{yyyyMMdd}.txt", but this didn't work either. Any ideas?

**Comment by chriswill** [comment]
There was an issue with formatting for the batching log sink provider, and this has been addressed in version 1.0.1, which is just appearing on nuget.  
Please try again with that version and see if that addresses your issue.

**Comment by chriswill** [comment]
@littleoz2 Closing this issue for now.  There is also a later release of 1.0.2 which has some additional changes for dealing with max blob pages and sizes.  Please let me know if you continue to see this problem.
