### ISSUE TITLE
Conflict when using Microsoft.Azure.Storage.Blob

### ISSUE THREAD

**Issue by jshinevar** [chriswill/serilog-sinks-azureblobstorage#28]
My application is using the latest Nuget packages for Azure Blob storage elsewhere.  This makes a conflict when I use Serilog.Sinks.AzureBlobStorage because of its dependency on Microsoft.WindowsAzure.Storage.  Is it possible to update this sink to use the latest Blob Nuget from https://www.nuget.org/packages/Microsoft.Azure.Storage.Blob/

**Comment by chriswill** [comment]
@jshinevar This project doesn't reference Microsoft.Azure.Storage.Blob directly.  It references WindowsAzure.Storage, but it requires version 9.0.0 *or higher*.  So if you want to use the sink with version 9.3.3 (the current version) there's nothing preventing that.
I'm not aware of what might be referencing Microsoft.Azure.Storage.Blob.

**Comment by jamesmundy** [comment]
I seem to be having this problem also, I have v9.3.3 of WindowsAzure.Storage installed but I get the following error:
```System.IO.FileNotFoundException: 'Could not load file or assembly 'Microsoft.WindowsAzure.Storage, Version=9.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.'```
I'll try downgrading to 9.0.0 tomorrow and see if that helps.

**Comment by jshinevar** [comment]
@chriswill I don't think anything is referencing Microsoft.Azure.Storage.Blob.  It should though because those are the new packages by Microsoft.  Microsoft.WindowsAzure.Storage has been updated and split out based on the type of storage.  It would be good for this sink to use the latest Nuget packages.  That is the conflict, I can't use Microsoft.Azure.Storage.Blob and this sink at the same time.  I would rather not downgrade my packages to older and eventually obsolete packages.

**Comment by chriswill** [comment]
@jshinevar Thanks for that info, I wasn't aware that WindowsAzure.Storage had split.  I can issue a new version that picks up Microsoft.Azure.Storage.Blob instead.

**Comment by chriswill** [comment]
I tried to update to Microsoft.Azure.Storage.Blob and thought it would be a quick adoption, but it wasn't successful.  The adoption wasn't hard but the sink wouldn't write any log entries.  That was the 1.2.1 release.  :)

I had to revert back to WindowsAzure.Storage, which is in the 1.2.3.  I'll see if I can have time to have another run at this again this weekend, or I'd invite you to try and submit a PR if you'd like to tackle.

**Comment by chriswill** [comment]
I finally figured out the conflict issue... The new Microsoft.Azure.Storage libraries only support from .Net 4.5.2 and higher, although nuget lists them as supporting 4.5.  So I just had to change the minimum framework version that the AzureBlobStorageSink supports to match and I eliminated these problems.

There will be a new version coming shortly with this, just as soon as I can look into a .[Net Framework issue](https://github.com/chriswill/serilog-sinks-azureblobstorage/issues/32).

**Comment by chriswill** [comment]
[Version 1.3.0](https://www.nuget.org/packages/Serilog.Sinks.AzureBlobStorage/1.3.0) is now our that has references to 10.0.0+ of Microsoft.Azure.Storage.

**Comment by syim1** [comment]
> My application is using the latest Nuget packages for Azure Blob storage elsewhere. This makes a conflict when I use Serilog.Sinks.AzureBlobStorage because of its dependency on Microsoft.WindowsAzure.Storage. Is it possible to update this sink to use the latest Blob Nuget from https://www.nuget.org/packages/Microsoft.Azure.Storage.Blob/

is Microsoft.WindowsAzure.Storage necessary if you want to use  Serilog.Sinks.AzureBlobStorage?

**Comment by chriswill** [comment]
No, versions 1.3.0 and higher use Microsoft.Azure.Storage.Blob

**Comment by syim1** [comment]
currently it's working without Microsoft.Azure.Storage.Blob, but I should add that package?

**Comment by chriswill** [comment]
The Serilog AzureStorageBlob library adds all the dependencies it needs, including this one, automatically. No need to manually add it unless you want to write your own Blob code in your app.
