### ISSUE TITLE
Blob not appending after upgrading

### ISSUE THREAD

**Issue by lukeb2** [chriswill/serilog-sinks-azureblobstorage#30]
I've been trying to get the rolling blob name functionality working and I realized I was a few revisions behind.  When I upgraded to 1.2.1 from 1.0.0.1 the blobs are created but they do not update. I followed the JSON format as you describe in the doc:
{
        "Name": "AzureBlobStorage",
        "Args": {
          "outputTemplate": "<my template>",
          "connectionString": "<my connection string",
          "storageContainerName": "serverlogs",
          "storageFileName": "{yyyy}/{MM}/{dd}/localInstance.txt"
}
The bob is created as the storageFileName dictates but no log entries are ever written to it.  If I switch back to 1.0.0.1 the blobs update as expected.  Any insight you may have would be appreciated.  Thanks

**Comment by chriswill** [comment]
There's a 1.2.3 package that is coming out of nuget right now.  Please update to that and try again.
In the 1.2.1 release I didn't make any code changes, but I adopted the latest Azure Storage libraries from Microsoft and there seemed to be a problem.
I don't use the same method of configuration that you do, but I was able to replicate the problem.
After you've added 1.2.3, please let me know if you continue to see an issue.

**Comment by lukeb2** [comment]
Thanks Chris, that fixed the issue.  I appreciate your help.  - Luke
