### ISSUE TITLE
Call to log writer never returns

### ISSUE THREAD

**Issue by mattjames-counterpart** [chriswill/serilog-sinks-azureblobstorage#32]
I'm trying to add Serilog logging to my project (ASP .NET Web Application (.NET Framework 4.6.1)) and I can't get it past the actual logging of the statement.
```	
var _logger = new LoggerConfiguration()
	.WriteTo.AzureBlobStorage( "DefaultEndpointsProtocol=https;AccountName=zzzzzzzz;AccountKey=xxxxxxx;EndpointSuffix=core.windows.net", Serilog.Events.LogEventLevel.Debug, "dev-logs", "{yyyy}/{MM}/{dd}/log.txt" )
	.CreateLogger();
_logger.Information( "testing" );
```
If I put a breakpoint in place, I can step over the `.CreateLogger()` statement, but if I try to step past the `.Information()` call, it never makes it to the next statement.  No exceptions are thrown, and the entry never makes it to the log file.  The file is created, but remains empty.  What am I missing?  I've tried this with version 1.2.3 and 1.1.1.  I've also tried both 2.7.1 and 2.8.0 of Serilog itself.  Is there something wrong with my connection string (in which case, how is the file created empty)?  What other settings or changes do I need to make in order to get this running properly?

Other packages that got added to my project:
..\packages\Microsoft.Azure.KeyVault.Core.1.0.0\lib\net40\Microsoft.Azure.KeyVault.Core.dll
..\packages\WindowsAzure.Storage.9.3.3\lib\net45\Microsoft.WindowsAzure.Storage.dll
..\packages\Newtonsoft.Json.12.0.1\lib\net45\Newtonsoft.Json.dll
..\packages\Serilog.2.8.0\lib\net46\Serilog.dll
..\packages\Serilog.Sinks.AzureBlobStorage.1.2.3\lib\net45\Serilog.Sinks.AzureBlobStorage.dll
..\packages\Serilog.Sinks.File.4.0.0\lib\net45\Serilog.Sinks.File.dll
..\packages\Serilog.Sinks.PeriodicBatching.2.1.1\lib\net45\Serilog.Sinks.PeriodicBatching.dll

**Comment by Albertyn** [comment]
Having a similar issue possibly. I'm using autofac to inject the logger into a controller. In a try catch block it logs the exception and I get it in the text file on Azure, but the app hangs and does not return a response. It seems like its waiting on something to wrap-up, tho I haven't had the patience to let it time out... 


            ILogger Logger = new LoggerConfiguration()
                .WriteTo.AzureBlobStorage(
                    ConfigurationManager.ConnectionStrings["blobstoreage"].ConnectionString,
                    Serilog.Events.LogEventLevel.Verbose, 
                    "webapi", 
                    "{yyyy}/{MM}/{dd}/bloblog.txt"
                    )
                .CreateLogger();
            var builder = new ContainerBuilder();

            builder.RegisterInstance<ILogger>(Logger);

then in the Controller


        readonly ILogger _log;
        public FaqController(ILogger log)
           : base()
        {
            _log = log;
        }


        [HttpGet]
        public List<Faq> GetFaqItems()
        {
            try { throw new Exception("some error boss"); }
            catch (Exception e)
            {
                try
                {
                    _log.Error("This is an event from 'FaqController': {@error}", e);
                }
                catch (Exception ex)
                {
                    var s = ex.Message;
                }
            }

            return new List<Faq>() {...}
        }

I've even put a try catch in the catch block to see what's up but no luck it just gets stuck on __log.Error_ in the debugger.

**Comment by chriswill** [comment]
@mattjames-counterpart Your configuration is fine and when I build the similar Logger up in the global.asax and log in that location, I can log with no issues.  

However when I try to log in a controller method like this: 
```
        public ActionResult Index()
        {
            Log.Logger.Information("Welcome to the home controller");
            return View();
        }
```
then I can see the behaviour where it hangs on the Log.Information line (although the log line does get written to the Azure blob).

I will try to dig into this.

**Comment by Albertyn** [comment]
I managed to get mine working by using the following configuration.
`

            ILogger Logger = new LoggerConfiguration()
                .WriteTo.AzureBlobStorage(
                    ConfigurationManager.ConnectionStrings["blobstoreage"].ConnectionString,
                    Serilog.Events.LogEventLevel.Verbose, 
                    "webapi", 
                    "{yyyy}/{MM}/{dd}/blob-log.txt",
                    null,
                    true,
                    TimeSpan.FromSeconds(15),
                    10,
                    true
                    )
                .CreateLogger();

`
The storage service offers three types of blobs, "block blobs", "append blobs", and "page blobs" - I set it up as Append and perhaps this feature does not reply to callers with a "confirm write" kind of response ... just my 5c

**Comment by brolaugh** [comment]
I've got this issue as well, although I've found that if time rolls into a new minute (e.g. 10:00 -> 10:01) then the file only gets created but doesn't get written to the Azure blob. I've only got two lines that does logging in my application at the moment which is in the Serilog setup within `Global.asax.cs` and a Controller like below.

```
private void InitializeLogging(){
    Log.Logger = new LoggerConfiguration()
                    .ReadFrom.AppSettings()
                    .CreateLogger();
    Log.Information("Logging has started"); // works fine
}
```

```
 public ActionResult Index()
        {
            Log.Logger.Information("Welcome to the home controller");
            return View();
        }
```

**Comment by brolaugh** [comment]
This issue still present in `1.4.0`.

**Comment by chriswill** [comment]
I have looked into this in the past, and I think I've commented above, that the library just hangs when it calls the Azure Storage library to write to the blob.  This never happened on netstandard2.0.

I'm closing this thread because I dropped support for net452.  If you can move your app to .net 4.7.2 you can have great netstandard2.0 support and this library should work.

**Comment by adityapewekar** [comment]
Hi,
Trying to use the functionality in my Blazor application. Whenever am calling logger function to log the message the method call do not proceed after the logger call. Below is my method
 ```
      void logmessages()
        {
            _logger.LogDebug("Logging Debug");
            _logger.LogError("Logging Error");
            _logger.LogTrace("Logging Trace");
            _logger.LogCritical("Logging Critical");
            _logger.LogInformation("Logging Information");
            _logger.LogWarning("Logging Warning");
        }
```

The method call just log Logging Debug ( or which ever is the first log function ) and the the function don't proceed and the page keeps loading.

Below is my appsetting.json
```

"Serilog": {
    "Using": [
      "Serilog.Sinks.AzureBlobStorage", "Serilog.Filters.Expressions"
    ],
    "MinimumLevel": {
      "Default": "Debug",
      "Override": {
        "Default": "Information",
        "Microsoft": "Warning",
        "Microsoft.Hosting.Lifetime": "Information"
      }
    },
    "WriteTo": [
      {
        "Name": "Logger",
        "Args": {
          "configureLogger": {
            "Filter": [
              {
                "Name": "ByIncludingOnly",
                "Args": {
                  "expression": "(@Level = 'Error' or @Level = 'Fatal' or @Level = 'Warning' or @Level = 'Information' or @Level = 'Debug')"
                }
              }
            ],
            "WriteTo": [
              {
                "Name": "AzureBlobStorage",
                "Args": {
                  "connectionString": "Valid connection string",
                  "storageContainerName": "My Log",
                  "storageFileName": "logFile.log",
                  "outputTemplate": "{Timestamp:yyyy-MM-dd hh:mm:ss} [{Level:u3}] ({SourceContext}) {Message}{NewLine}{Exception}"
                }
              }
            ]
          }
        }
      }
    ],
    "Enrich": [
      "FromLogContext",
      "WithMachineName",
      "WithProcessId",
      "WithThreadId"
    ],
    "Properties": {
      "Application": "MyApp"
    }
  }
```

Below is my code for Program.cs

 ```
       public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
            .ConfigureLogging((hostingContext, logging) =>
            {
                var logger = new LoggerConfiguration()
                     .ReadFrom.Configuration(hostingContext.Configuration)
                     .CreateLogger();

                logging.AddSerilog(logger,dispose:true);
            })
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                });
```

**Comment by GCoding83** [comment]
I have the exact same problem. In my Blazor application, the logger will only read the first logging line and then my application will freeze (load endlessly). The problem ceases to happen if I just remove the .WriteTo.AzureBlobStorage bit in my logger configuration.

Help?

**Comment by adityapewekar** [comment]
Using [Serilog Async](https://github.com/serilog/serilog-sinks-async) solved my problem

**Comment by GCoding83** [comment]
Thanks for the heads up @adityapewekar.

I am running into a problem when attempting to configure the async version. Here is my code:

![image](https://user-images.githubusercontent.com/48444806/106005990-c5792d00-6082-11eb-86c6-39efc52a346a.png)

I get an ArgumentNullException specifying that the value for connectionString cannot be null. Did you run into this problem yourself? Any thoughts?

Thanks.

**Comment by adityapewekar** [comment]
Hi @GCoding83 

Please refer the below link for my implementation. The approach is bit different but its worked at my end.
https://github.com/chriswill/serilog-sinks-azureblobstorage/issues/70#issuecomment-768818145

**Comment by jassent** [comment]
> Thanks for the heads up @adityapewekar.
> 
> I am running into a problem when attempting to configure the async version. Here is my code:
> 
> ![image](https://user-images.githubusercontent.com/48444806/106005990-c5792d00-6082-11eb-86c6-39efc52a346a.png)
> 
> I get an ArgumentNullException specifying that the value for connectionString cannot be null. Did you run into this problem yourself? Any thoughts?
> 
> Thanks.

Try moving the Configuration.GetValue out of inline code to verify you are receiving the connection string. What you have written is working for me (except that I load the connection string into a variable and then use the variable inline). I am using the same method as you:
`var storageConn = config.GetValue<string>("AppConfiguration:StorageConnectionString");`
