### ISSUE TITLE
What governs the size of blobs? I see new files (-001, -002, etc) created after the original blob reaches a certain size but that value seems to vary. is there a config setting that dictates the max size of a blob file?

### ISSUE THREAD

**Issue by lukeb2** [chriswill/serilog-sinks-azureblobstorage#33]

**Comment by chriswill** [comment]
An individual append blob is made up of blocks and each block can be up to 4mb in size.  There are a maximum of 50,000 blocks in a single blob.  But, an append blob can have a maximum total size of 195gb.

[Append blob details](https://docs.microsoft.com/en-us/rest/api/storageservices/understanding-block-blobs--append-blobs--and-page-blobs#about-append-blobs)

The sink will generate a new file if you are approaching the limit in number of blocks in your append blob OR the total overall size that an append blob can support.

I'm guessing in your case you are likely rolling over based on the number of blocks in your append blob.
