### ISSUE TITLE
Doesn't append to blob

### ISSUE THREAD

**Issue by Nohcho** [chriswill/serilog-sinks-azureblobstorage#36]
I can't seem to get it working. It does create the container and the blob, but nothing is appended to the blob. I'm using the ILogger interface. In Application Insights I see 409 when it tries to log. Must be something that I do wrong.. but I just cant see what it is..

Using netcoreapp2.2.
`Serilog Version="2.8.0"`
`Serilog.AspNetCore Version="2.1.1"`
`Serilog.Sinks.AzureBlobStorage Version="1.3.0"`

**Program.cs**
```
WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>()
                .UseSerilog((context, configuration) =>
                    {
                        configuration
                            .MinimumLevel.Debug()
                            .MinimumLevel.Override("Microsoft", LogEventLevel.Warning)
                            .MinimumLevel.Override("System", LogEventLevel.Warning)
                            .MinimumLevel.Override("Microsoft.AspNetCore.Authentication", LogEventLevel.Information)
                            .Enrich.FromLogContext()
                            .WriteTo.AzureBlobStorage(CloudStorageAccount.Parse(context.Configuration.GetConnectionString("StorageAccount")), LogEventLevel.Information, null, "{yyyy}/{MM}/{dd}/log.txt")
                            .WriteTo.Console(outputTemplate: "[{Timestamp:HH:mm:ss} {Level}] {SourceContext}{NewLine}{Message:lj}{NewLine}{Exception}{NewLine}", theme: AnsiConsoleTheme.Literate);
                    });
```

**Comment by Nohcho** [comment]
Just wated to add that I've tested my logging using the Serilog.Sinks.File and it works fine.

**Comment by tiagopalves** [comment]
I'm having the same issue.

Working with Serilog.Sinks.File too, but not appending on AzureBlobStorage.

I'm using a config file like this:
  "Serilog": {
    "Using": [
      "Serilog.Sinks.AzureBlobStorage"
    ],
    "MinimumLevel": {
      "Default": "Verbose",
      "Override": {
        "Microsoft": "Verbose",
        "System": "Verbose"
      }
    },
    "WriteTo": [
      {
        "Name": "AzureBlobStorage",
        "Args": {
          "connectionString": "DefaultEndpointsProtocol=...",
          "storageContainerName": "logs",
          "storageFileName": "{yyyy}/{MM}/{dd}/log.pocserilog.txt",
          "retainedFileCountLimit": 31
        }
      }
    ],
    "Enrich": [ "FromLogContext" ]
  }

**Comment by tiagopalves** [comment]
Guys, i just tested the version 1.2.3 and it worked!

So, the problem is with the new version 1.3.0, maybe the same problem with Azure libs that you had before.

**Comment by chriswill** [comment]
I'm pushing out a new version 1.4.0 based on a PR that @alexeysas contributed.  I believe it will solve these problems.  Please reopen this thread if you still see issues.

**Comment by tiagopalves** [comment]
I tested the new version and it works!

Thanks for the help guys!
