### ISSUE TITLE
Add support for using date fields multiple times

### ISSUE THREAD

**Issue by brolaugh** [chriswill/serilog-sinks-azureblobstorage#40]
I'm currently in the process of implementing this project. What would really help me is if this library supported having each date part multiple times to allow formats like this: 
```
{yyyy}/{MM}/{dd}/{yyyy}-{MM}-{dd}_{HH}:{mm}.txt
2019/06/20/2019-06-20_14:40.txt
```
This would help in identifying log files which has been downloaded and no longer has the folder named to give it context. One could put all the date fields into the file name but that would potentially create **HUGE** leaf folders in terms of the amount of files.

**Comment by chriswill** [comment]
Thanks to @adementjeva this is now complete
