### ISSUE TITLE
Rolling log file by size

### ISSUE THREAD

**Issue by TaylorN15** [chriswill/serilog-sinks-azureblobstorage#41]
From what I can see, there's no option for a rolling file with a size limitation, like there is in the File sink. Is this possible?

Also, how do I specify the additional parameters (line format, blob container, and blob name) when using the AppSettings method?

**Comment by chriswill** [comment]
Thanks to @stackad , rolling files based on size is now available in version 2.0.2

There are general instructions on how to load settings based on appsettings.json on the main readme.  If you have specific questions, please open a new question.
