### ISSUE TITLE
Managed Idenity / Key Vault

### ISSUE THREAD

**Issue by bbakermmc** [chriswill/serilog-sinks-azureblobstorage#42]
Can you add an example of using a Managed Identity to access the blob and/or pulling the connection string from a Key Vault.

Storing the account key in plain text is bad.  SAS is slightly better ;), but since the app is running in azure with a managed id, and we can configure sql to not use a password, and our other file access using MI to the storage account, this logging should also access it the same way.

https://docs.microsoft.com/en-us/azure/storage/common/storage-auth-aad-msi

**Comment by bradforddillon** [comment]
So this is how I have gotten it working with managed identities. Tokens are only valid for an hour, so I also provided a token refresh delegate. Refresh is set for 30 minutes in this code, but you can set it to whatever you think is best. 
    
    using Microsoft.Azure.Services.AppAuthentication;

    public async Task<CloudStorageAccount> CreateCloudStorageAccount()
    {
        var tokenProvider = new AzureServiceTokenProvider();
        var token = await tokenProvider.GetAccessTokenAsync("https://storage.azure.com").ConfigureAwait(false);
        var tokenCredential = new TokenCredential(token, RefreshToken, null, TimeSpan.FromMinutes(30));
        var storageCredentials = new StorageCredentials(tokenCredential);
        var account = new CloudStorageAccount(storageCredentials, "<storageaccountnamehere>, "core.windows.net", true);

        return account;
    }

    public async Task<NewTokenAndFrequency> RefreshToken(object state, CancellationToken cancellationToken) 
    {
        var tokenProvider = new AzureServiceTokenProvider();
        var token = await tokenProvider.GetAccessTokenAsync("https://storage.azure.com").ConfigureAwait(false);

        return new NewTokenAndFrequency(token, TimeSpan.FromMinutes(30));
    }

This is how I've gotten it working with Key Vault storing the connection string.

    using Microsoft.Azure.KeyVault;
    using Microsoft.Azure.Services.AppAuthentication;

    public static async Task<string> GetLogStorageConnectionString()
    {
        var tokenProvider = new AzureServiceTokenProvider();
        var keyVaultClient = new KeyVaultClient(new KeyVaultClient.AuthenticationCallback(tokenProvider.KeyVaultTokenCallback));
        var secretUrl = "<fully qualified URL to secret here>";

        return (await keyVaultClient.GetSecretAsync(secretUrl).ConfigureAwait(false)).Value;
    }

The first method gives you a `CloudStorageAccount` to pass to the sink. The second gives you a connection string. 

Hope that helps.

**Comment by PiotrPerak** [comment]
@bradforddillon Thank you so much for this code. I had no idea that I should refresh this token expires. I hope this will solve my problem of logging stopping to work after some time.

Can you point me to documentation that says it's valid for 1 hour? I think that it was working for longer then 1 hour after restart.
