### ISSUE TITLE
Batch JSON Config Example

### ISSUE THREAD

**Issue by bbakermmc** [chriswill/serilog-sinks-azureblobstorage#43]
Can you provide a Batch JSON Config Example.

**Comment by vivek-spoon** [comment]
I am also in need of this!

**Comment by chriswill** [comment]
This PR was just posted that added documentation on the batch posting configuration: https://github.com/chriswill/serilog-sinks-azureblobstorage/pull/80.  Please take a look at the README.MD and see if this helps.
