### ISSUE TITLE
Combine appsettings.json with runtime configuration

### ISSUE THREAD

**Issue by lucasmaj** [chriswill/serilog-sinks-azureblobstorage#47]
I like having Serilog configured in appsettings.json, for example
```JSON
{
  "Serilog": { 
    "Using": [
      "Serilog.Sinks.AzureBlobStorage"
    ],
    "WriteTo": [
      {
        "Name": "AzureBlobStorage",
        "Args": {
          //"connectionString": "I wish to come from environment variables",
          "storageContainerName": "SomeContainer",
          "outputTemplate": "[{Timestamp:HH:mm:ss} {Level:u3} {SubscriptionName,-10}] {Message:lj} {NewLine}{Exception}",
          "storageFileName": "logs/{yyyy}-{MM}-{dd}-{HH}.txt"
        }
      }
    ]
  }
}
```

At the same time I would like to configure the connection string at runtime, or leave the connection string in appsettings.json but substitutue storage account name and key with environment variables.

I have tried the approach of building configuration twice, where first 

```C#
var configurationBuilder = new ConfigurationBuilder()
    .AddJsonFile("appsettings.json", false, true)
    .AddEnvironmentVariables();
```

then create the storage connection string and finally 

```C#
configurationBuilder.AddInMemoryCollection(new[] { 
    new KeyValuePair<string, string>(
        "Serilog:WriteTo:AzureBlobStorage.connectionString", 
        storageConnectionString)});
```

but that key is not "hitting" the right field for Serilog configuration to pickup it up.

Any ideas?

**Comment by chriswill** [comment]
All of the configuration options you mention are handled by a different package - https://github.com/serilog/serilog-settings-configuration.

If you want to see enhancements to json settings handling, you should post to that repo.

**Comment by lucasmaj** [comment]
Will do, thanks.

**Comment by lucasmaj** [comment]
I ended up with this solution: https://github.com/serilog/serilog-settings-configuration/issues/102#issuecomment-561850614
