### ISSUE TITLE
Rolling file cleanup

### ISSUE THREAD

**Issue by ochoquette** [chriswill/serilog-sinks-azureblobstorage#49]
Hello, 

Is there any plans to implement some sort of automatic cleanup of the rolling files like in the [File Sink](https://github.com/serilog/serilog-sinks-file#rolling-policies)?

Thanks

Olivier

**Comment by chriswill** [comment]
Oliver, I’d be happy to take a pull request :)

It’s a nice feature.

Sent from my iPhone

On Feb 21, 2020, at 1:18 PM, ochoquette <notifications@github.com> wrote:

﻿

Hello,

Is there any plans to implement some sort of automatic cleanup of the rolling files like in the File Sink<https://github.com/serilog/serilog-sinks-file#rolling-policies>?

Thanks

Olivier

**Comment by chriswill** [comment]
The property retainedBlobCountLimit should control this.
