### ISSUE TITLE
Azurite for testing

### ISSUE THREAD

**Issue by ie-zero** [chriswill/serilog-sinks-azureblobstorage#54]
The latest version (v3.7) of Azurite support append blobs. I have not used Azurite in any capacity but would you consider using it for testing?

https://github.com/Azure/Azurite/releases

**Comment by chriswill** [comment]
I've used Azurite on other projects for testing of regular blobs.  It's a fantastic library.  I'll definitely add some Azurite tests, or you can submit a PR if you'd like to contribute some.
