### ISSUE TITLE
Instructions about how to store the log data as JSON

### ISSUE THREAD

**Issue by jfalameda** [chriswill/serilog-sinks-azureblobstorage#55]
Hi,

I do not see any information regarding how to store the log data as JSON in the file. It would be great to add some instructions.

Kind Regards,
José.

**Comment by chriswill** [comment]
Log formatters like this one, and the Serilog File Sink don't generally log in Json.  But I *think* you should be able to do it, using something like this https://github.com/serilog/serilog/wiki/Formatting-Output#formatting-json

I think it would be difficult to set up in appsettings configuration, but you should be able to make progress with programmatic configuration.  Let me know how it goes and I'll post your solution.

**Comment by jfalameda** [comment]
Thanks!

This was very helpful.
