### ISSUE TITLE
Log file not being created

### ISSUE THREAD

**Issue by mtazbinur** [chriswill/serilog-sinks-azureblobstorage#62]
Hello @chriswill ,

I was just trying out this library. But I am facing an issue where a blob container is being created, but I can't find any log files under that container. Not sure what exactly went wrong. I am using .NET Core 3.1 and Microsoft Azure Storage Emulator for local development btw.

Here is the code snippet I am using:
````
var bn = new BlobNameFactory("{yyyy}/{MM}/{dd}_V2_Info.txt");
 var log = new LoggerConfiguration()
                 .WriteTo.AzureBlobStorage(connectionString, LogEventLevel.Information,"logs",bn.GetBlobName(new DateTimeOffset((DateTime.Now))))
                 .CreateLogger();

log.Information("test information log");
````

**Comment by danielwertheim** [comment]
Use the Azurite emulator. The other emulator does not support append blobs.

**Comment by mtazbinur** [comment]
@danielwertheim thanks a lot for the help. The problem is now resolved. Hence I am closing this issue.
