### ISSUE TITLE
named connection string from connections strings section doesn't work

### ISSUE THREAD

**Issue by slavapvf** [chriswill/serilog-sinks-azureblobstorage#63]
Hello,
I expected to use named connection string from connections strings section like that is used in mssql sink but it doesn't work for azureblobstorage. could you please help. https://github.com/serilog/serilog-sinks-mssqlserver/issues/150

**Comment by chriswill** [comment]
Currently that is not the way that the sink operates. It more closely follows the Serilog [Azure Table Storage sink](https://github.com/serilog/serilog-sinks-azuretablestorage).

If you wanted to submit a PR, I would suggest a parameter such as "connectionStringName" to allow existing implementations to continue to function.
