### ISSUE TITLE
Empty log.txt file created on Azure Data Lake (built on Azure Blob Storage)

### ISSUE THREAD

**Issue by jkiezun** [chriswill/serilog-sinks-azureblobstorage#64]
I am using Azure Functions and want to save my logs on Azure Data Lake gen2, logging to console and local file works fine, logging to Data Lake gen2 (which is basically blob storage) only creates folders and empty "log.txt" file with size of 0B and type of append blob. Do you know the reason? I see a similar issue over a year ago regarding WebJobs and it is not resolved.
```
public class Startup : FunctionsStartup
    {
        public override void Configure(IFunctionsHostBuilder builder)
        {
            string connectionString = "myConnectionString";
            var logger = new LoggerConfiguration()
                .WriteTo.Console()
                .WriteTo.File("log.txt", rollingInterval: RollingInterval.Minute)
                .WriteTo.AzureBlobStorage(connectionString, Serilog.Events.LogEventLevel.Information, null, "{yyyy}/{MM}/{dd}/log.txt")
                .CreateLogger();
            builder.Services.AddLogging(lb => lb.AddSerilog(logger));
}
```

**Comment by chriswill** [comment]
Append Blob support in Azure Data Lake is [now generally available](https://azure.microsoft.com/en-us/updates/append-blob-support-in-azure-data-lake-storage-is-now-generally-available/), so this library will now work there.  The lack of append blob support was the reason why this didn't work in Nov 2020.
