### ISSUE TITLE
JSON configuration is not working in .netcore console app

### ISSUE THREAD

**Issue by abidalis** [chriswill/serilog-sinks-azureblobstorage#65]
Hello,

I have created simple .netcore 2.2 console app and try to configure using JSON configuration but it's not working. 

Here is my .csproj package reference.

`<ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="2.2.0" />
    
    <PackageReference Include="Serilog.Settings.Configuration" Version="3.1.0" />
    <PackageReference Include="Serilog.Sinks.Async" Version="1.4.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="3.1.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="4.0.0" />
    <PackageReference Include="Serilog.Sinks.AzureBlobStorage" Version="2.0.2" />
  </ItemGroup>`

Here is appsettings.json configuration

`{
  "Serilog": {
    "Using": [ "Serilog.Sinks.AzureBlobStorage" ],
    "MinimumLevel": "Verbose",
    "WriteTo": [
      {
        "Name": "Async",
        "Args": {
          "configure": [
            {
              "Name": "Console",
              "Args": {
                "theme": "Serilog.Sinks.SystemConsole.Themes.AnsiConsoleTheme::Code, Serilog.Sinks.Console",
                "outputTemplate": "{Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} [{Level:u3}] {Message:j}{NewLine}{Properties:j}{NewLine}{Exception}"
              }
            },
            {
              "Name": "File",
              "Args": {
                "restrictedToMinimumLevel": "Warning",
                "path": "D:\\Logs\\Test_log.txt",
                "rollingInterval": "Day",
                "fileSizeLimitBytes": 10240,
                "rollOnFileSizeLimit": true,
                "retainedFileCountLimit": 30
              }
            },
            {
              "Name": "AzureBlobStorage",
              "Args": {
                "connectionString": "[Connection string]",
                "storageContainerName": "logs",
                "storageFileName": "test-logs-{dd-MM-yyyy}.txt",
                "blobSizeLimitBytes": "4000000",
                "restrictedToMinimumLevel":  "Information"
              }
            }
          ]
        }
      }
    ],
    "Enrich": [ "FromLogContext", "WithMachineName", "WithExceptionDetails" ],
    "Properties": {
      "ApplicationName": "SampleApp",
      "Environment": "Dev"
    }
  }
}`

Here is the code to create logger and use it.

`var configuration = new ConfigurationBuilder()
                    .AddJsonFile("appsettings.json")
                    .Build();`

`Log.Logger = new LoggerConfiguration()
	.ReadFrom.Configuration(configuration)
	.CreateLogger();`
	
`Log.Verbose("Here's a Verbose message.");
Log.Information(new Exception("Exceptions can be put on all log levels"), "Here's an Info message.");`

Please let me know if I'm missing something.

Thanks,
Abid Ali

**Comment by sdsalyer** [comment]
Perhaps a year too late, but I believe if you make the below change it will work:

```json
"storageFileName": "test-logs-{dd}-{MM}-{yyyy}.txt"
```
