### ISSUE TITLE
File doesn't rollover when reaching file size limit 

### ISSUE THREAD

**Issue by MarcDeRaedt** [chriswill/serilog-sinks-azureblobstorage#71]
After reaching a configured file size limit the file doesn't rollover. After stopping and starting the application a new file is created. It seems the file size is only determined once. A solution can be fetching the filesize more often. Tested the solution as shown below and this seems to work (only added fetchAttributes marked in bold). Can someone agree that this is the wright solution and maybe fix this ?

The code change is done in the class DefaultCloudBlobProvider.

public async Task<CloudAppendBlob> GetCloudBlobAsync(CloudBlobClient cloudBlobClient, string blobContainerName, string blobName, bool bypassBlobCreationValidation, long? blobSizeLimitBytes = null)
{
    // Check if the current known blob is the targeted blob
    if (currentCloudAppendBlob != null && currentBlobName.Equals(blobName, StringComparison.OrdinalIgnoreCase))
    {
        **await currentCloudAppendBlob.FetchAttributesAsync().ConfigureAwait(false);**
        // Check if the current blob is within the block count and file size limits
        if (ValidateBlobProperties(currentCloudAppendBlob, blobSizeLimitBytes))
        {                    
            return currentCloudAppendBlob;
        }
        else
        {
            // The blob is correct but needs to be rolled over
            currentBlobRollSequence++;
            await GetCloudAppendBlobAsync(cloudBlobClient, blobContainerName, blobName, bypassBlobCreationValidation);
        }
    }
    else
    {
        //first time to get a cloudblob or the blobname has changed
        currentBlobRollSequence = 0;
        await GetCloudAppendBlobAsync(cloudBlobClient, blobContainerName, blobName, bypassBlobCreationValidation, blobSizeLimitBytes);
    }

    return currentCloudAppendBlob;
}

**Comment by YauheniBarodzich** [comment]
Hello @MarcDeRaedt , 
I've implemented interface `ICloudBlobProvider` as `TestLoggingCloudProvider` adding your line of the code `await currentCloudAppendBlob.FetchAttributesAsync().ConfigureAwait(false);` in my project and injected into logger configuration `.WriteTo.AzureBlobStorage(cloudBlobProvider: new TestLoggingCloudProvider(),..)`. 
It works perfectly! 
New files are created once exceeding the limit of defined bytes.

**Comment by chriswill** [comment]
I've merged this pull request and the nuget package 2.1.1 is being published that will contain this fix.  Thanks to @MarcDeRaedt for creating the PR and to @YauheniBarodzich for verifying the fix.
