### ISSUE TITLE
Call to log writer never returns in Blazor application (from Issue #32)

### ISSUE THREAD

**Issue by GCoding83** [chriswill/serilog-sinks-azureblobstorage#72]
Hi,

A problem was raised at the end of Issue #32, which was closed because it initially concerned only pre-.NET Standard 2.0 applications. The very same problem arises in Blazor applications. The application stops reading logs after the first line read, and it then loads endlessly. Help would be greatly appreciated.

**Comment by chriswill** [comment]
I can't foresee a time when I'd have the availability to debug into what's happening with Blazor applications.  I'm sorry it's not working for you, but given that there is source available here, please post what you find when look into it.

**Comment by GCoding83** [comment]
Thanks for the quick reply Chris. I totally understand what you're saying. No worries at all.

Just a quick clarification if you don't mind. You wrote "I'm sorry it's not working _for you_". To your knowledge, does the Sink work on Blazor for other people?

**Comment by chriswill** [comment]
Unfortunately I've never heard of any feedback, one way or the other, from Blazor developers.

**Comment by GCoding83** [comment]
Got it thanks. Not sure I'll find the time to work on this myself. If someone else out there can find the time, that would be great. In the meantime, I'll just use the File Sink.

**Comment by dalian-spacekey** [comment]
I have the same problem. 
.NET 8 Blazor Server
It seems to occur when writeInBatches is set to false.
When it is set to true, I haven't tested it much yet, but so far, it appears to be working correctly.

**Comment by chriswill** [comment]
I don't think I have any plans on testing in the Blazor environment, so closing for now
