### ISSUE TITLE
Batch posting not working using JSON configuration

### ISSUE THREAD

**Issue by abidalis** [chriswill/serilog-sinks-azureblobstorage#75]
Hello,

I have used `Serilog.Sinks.AzureBlobStorage` to write log in Blob storage. It's working fine. Now, I have performance issue. So, as per documentation, I tried to enable [batch posting](https://github.com/chriswill/serilog-sinks-azureblobstorage/tree/67379594771c70e88a1d248e4caa31d8b3739392#batch-posting-example) using (_**writeInBatches**_) following JSON configuration.

> `{
        "Name": "AzureBlobStorage",
        "Args": {
          "connectionString": "BLOB ConnectionString",
          "storageContainerName": "test",
          "storageFileName": "{yyyy}/{MM}/Testlog-{yyyyMMdd}.txt",
          "writeInBatches": true,
          "restrictedToMinimumLevel": "Information"
        }
      }`

When I enable batch posting by setting `writeInBatches: true` it's throwing out without any exception from [here](https://github.com/chriswill/serilog-sinks-azureblobstorage/blob/67379594771c70e88a1d248e4caa31d8b3739392/src/Serilog.Sinks.AzureBlobStorage/Sinks/AzureBlobProvider/DefaultCloudBlobProvider.cs#L142). If I set it back to `writeInBatches: false`, it's working fine.

Please let me know if there is any issue in JSON configuration.

**Comment by chriswill** [comment]
This pull request was just added showing some documentation on how batch posting can be configured: https://github.com/chriswill/serilog-sinks-azureblobstorage/pull/80
