### ISSUE TITLE
Subsequent statements are not logged

### ISSUE THREAD

**Issue by jvanderbiest** [chriswill/serilog-sinks-azureblobstorage#8]
When trying to log more statements in the same method, the subsequent statements are not logged. 
For example, if you run the [testclient](https://github.com/chriswill/serilog-sinks-azureblobstorage/tree/master/test/AzureBlobStorage.TestClient), you could add an extra logging statement
```
Log.Information("Hello World!");
Log.Information("This line is never logged!");
```

You will see that only the first line will get logged

The example runs:
Serilog v2.6.0
Serilog.Sinks.AzureBlobStorage v0.8.15
Serilog.Sinks.PeriodicBatching v2.1.1

Thanks for the blob sink implementation @chriswill !!

**Comment by chriswill** [comment]
Thanks for the report about this issue.  I duplicated the problem and built the 1.0.0.1 release with a fix.  It should be coming out of nuget shortly.
