### ISSUE TITLE
Named ConnectionString not working

### ISSUE THREAD

**Issue by maxcl10** [chriswill/serilog-sinks-azureblobstorage#81]
I'm currently defining my connection strings the my appsettings .
```
"ConnectionStrings": {
    "AzureBlob": ""
  }
```
I want to use the name of my connection string in my sink configuration.
```
      {
        "Name": "Logger",
        "Args": {
          "configureLogger": {
            "WriteTo": [
              {
                "Name": "AzureBlobStorage",
                "Args": {
                  "connectionString": "AzureBlob",
                  "storageContainerName": "audit",
                  "storageFileName": "API/{yyyy}/{MM}/{dd}/logs.txt"
                }
              }
            ]
          }
        }
      }
```
It seems that this is not working. Or am I doing something wrong?

**Comment by chriswill** [comment]
It's not implemented that way; it expects the actual connection string.  The implementation was taken from the Azure Table Storage sync, which this was originally forked from.

If you'd like to make a PR to add this functionality, it would be helpful.
