### ISSUE TITLE
version 3+ requires .net standard 2.1?

### ISSUE THREAD

**Issue by Wagnerxyz** [chriswill/serilog-sinks-azureblobstorage#82]
Hi,

when i  upgrade from v2.1 to v3.0 , nuget install faied. can't support .netframework 4.8.
I saw  nuget  dependencies require .net standard 2.1.
why not support .net standard 2.0(.net framework 4.8)?
Azure.Storage.Blobs v12 only require .net standard 2.0

**Comment by chriswill** [comment]
It looks like this got introduced by the contributor during the conversion to the new Microsoft Storage libraries.  I've revised the code so the main library can support netstandard2.0.  The 3.0.2 version of the library is building now and will be available on nuget shortly.
