### ISSUE TITLE
Ability to set the Content Type of the files

### ISSUE THREAD

**Issue by jijothomas27** [chriswill/serilog-sinks-azureblobstorage#84]
Currently, the content type of file files added to the azure storage is application/octet-stream. This is the default content type for any blob being added to azure storage blob container. 
Custom Content Type of a blob can only be set when creating the blob. Can we have a configuration setting called "ContentType". When this value is set, the blobs created should have the contenttype mentioned in the configuration?

**Comment by chriswill** [comment]
Thanks for the suggestion.

What's the use case for this feature?  Is there some functionality you're missing with application/octet-stream?  And if you were to be able to change it, what would you set it at?

**Comment by chriswill** [comment]
No one seems to want this.
