### ISSUE TITLE
Microsoft.Azure.Storage.Blob deprecated.

### ISSUE THREAD

**Issue by heroes3lover** [chriswill/serilog-sinks-azureblobstorage#88]
One of dependency Microsoft.Azure.Storage.Blob is deperated.
Can this package be replaced with Azure.Storage.Blobs?
Thanks.

**Comment by chriswill** [comment]
Hi, what version are you using?  Version 3.0.0 and higher already uses Azure.Storage.Blobs.

**Comment by heroes3lover** [comment]
Sorry for delay, my version 1.4.0. Thank for let me know, I will upgrade my version to 3.0.0

**Comment by chriswill** [comment]
Current version is 3.1.1 I believe.  I would recommend that.
